# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BannerSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BannerSample
	pod 'InMobiSDK'

end

target 'BannerSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BannerSwiftSample
	pod 'InMobiSDK'

end
