# Uncomment the next line to define a global platform for your project
# platform :ios, 11.0'

target 'InterstitialSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InterstitialSample
	pod 'InMobiSDK'

end

target 'InterstitialSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InterstitialSwiftSample
	pod 'InMobiSDK'

end
