# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'NativeSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeSample
	pod 'InMobiSDK'

end

target 'NativeSampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeSampleSwift
	pod 'InMobiSDK'

end
