# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

def commonPods
    pod 'InMobiSDK'
end

target 'InMobiAdsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InMobiAdsDemo
  commonPods

  target 'InMobiAdsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InMobiAdsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

